name: Build
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release Tag'     
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Download JI jar
        run: |
          mkdir -p jars
          wget -O jars/ij-1.53c.jar https://repo1.maven.org/maven2/net/imagej/ij/1.53c/ij-1.53c.jar
      - name: Build the plugin
        run: |
          ./buduj.sh ./
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: IJ Plugin
          path: ./dist/*
          retention-days: 32
      - name: Release
        uses: softprops/action-gh-release@v1
        if: "${{ github.event.inputs.tag_name != '' }}"
        with:
          files: dist/*
          draft: false
          tag_name: ${{ github.event.inputs.tag_name }}
          fail_on_unmatched_files: true
          target_commitish: ${{ env.commit_hash }}
          generate_release_notes: true
  
